### ISSUE TITLE
What if acc using email instead of steam auth ?

### ISSUE THREAD

**Issue by idevmans** [Refloow/Steam-Games-Idle#1]
Can you make another feature if you do not have steam app guard and use email just type steam guard code from email ?

**Comment by Refloow** [comment]
Soon we will release update on this and our other project where we add more features and add branch to project (separate version of bot) that support multiple accounts on both of our projects.

When update get released we will patch that issue by adding option in config to set guard to false so bot will use alternative code from email.

Currently we are busy developing many other projects so update may get released in couple of days with new Professional Donation Bot that we coded.

**Comment by Refloow** [comment]
Fix 1.0.1 is out. We added new login method and option in config that allows you to set 2FA code verification to off that way bot asks you to enter codes manualy upon bot start. Thanks for giving suggestion and improving our project.

Patch to fix this issue is released now, our other bot and new version of software that supports multiple accounts will be released in near future since we still have some work to do.
